[line_break]
disabled = true

format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$package\
$c\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nodejs\
$ocaml\
$perl\
$php\
$python\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$meson\
$spack\
$openstack\
$status\
$shell\
$character"""

